packages:
  - apps/*
  - packages/*

catalogMode: prefer

catalog:
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest

overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
